### ISSUE TITLE
Doesn't seem to be able to handle standard Solana wallets?

### ISSUE THREAD

**Issue by mikemaccana** [solana-dev-adv/solana-dapp-next#27]
Hi! I was hoping to use this project similar to the wallet standard demo at https://solana-labs.github.io/wallet-adapter/example/:

![image](https://user-images.githubusercontent.com/172594/228873467-2da66c35-dad0-4339-af19-1db23f549596.png)

Ie, showing any wallet that has been registered with the wallet standard. But instead of showing the installed wallets and their icons, I get a list of well known older Solana wallets. I'm not sure what the expectation is here - does Solana dDapp Next handle the wallet standard?

**Comment by DonnySolana** [comment]
please use : [Solana Dapp Scaffold](https://github.com/solana-labs/dapp-scaffold/)

**Comment by mikemaccana** [comment]
Thanks @DonnySolana I appreciate the README update too. I’ll get  the project that linked here to link to the new repo too.

**Comment by mikemaccana** [comment]
https://github.com/solana-labs/wallet-adapter/pull/760
