### ISSUE TITLE
Here's how to run this against localhost 

### ISSUE THREAD

**Issue by cavanex** [solana-dev-adv/solana-dapp-next#5]
I'm not sure where to put this, but I had been dealing with this issue for a while and got it figured out. It turns out you need to have a commitment of 'processed' to be able to send transactions with your wallet on localhost!

Add lines below `const endpoint = ...` to have the following:
```
const localhost = "http://127.0.0.1:8899"
    let commitment: Commitment = 'processed'
    let config: ConnectionConfig = {
        commitment: commitment
    }
```

Updated your ConnectionProvider object in the ContextProvider.tsx file:
`        <ConnectionProvider endpoint={localhost} config={config}>
`

Make sure your `solana-test-validator` is running.

**Comment by lisenmayben** [comment]
this would be great if we could add this as a configurable UI component where we can select the network from a UI setting. let me know if you might be interested in this. otherwise Ill be adding this as one of the few issue/features to be completed!

**Comment by lisenmayben** [comment]
created a new issue if you would like to work on it.
